Add bundling of 3rdparty apps for receipt-scanner
danschultzer/blazing-bookkeeper pull request #7
Opened 2016-09-28 07:28 UTC by danschultzer

Resolves #2 

To-do:
- [ ] Remove unecessary files

2016-10-01 00:56 UTC, danschultzer commented
Release builds now work, but with one caveat. To build it, you need to define `PKG_CONFIG_PATH`. Run:

```sh
PKG_CONFIG_PATH=$(pwd)/thirdparty/opencv/lib/pkgconfig npm run release
```

This should be included somewhere in the dev setup though so it happens automatically.

Current file size is 389.6 MB. Breakdown:

- `app.asar`: 78.5 MB
- `electron`: 116.9 MB
- `thirdparty`: 194.7 MB
  - `thirdparty/dependencies`: 29.8 MB
  - `thirdparty/opencv`: 53.7 MB
  - `thirdparty/opencv`: 14.8 MB
  - `thirdparty/tesseract`: 96.4 MB

2016-10-01 18:42 UTC, danschultzer commented
Overall this PR is ready for 👀, and can be shipped. There're a few minor things that can be done, namely removing all unnecessary files. We can probably remove 20MB+.

2016-10-07 00:01 UTC, danschultzer commented
Current file size is 332.8 MB. Breakdown:

- `app.asar`: 49.6 MB
- `thirdparty`: 174.8 MB
  - `thirdparty/dependencies`: 20.7 MB
  - `thirdparty/opencv`: 43.6 MB
  - `thirdparty/opencv`: 14.8 MB
  - `thirdparty/tesseract`: 95.6 MB
  

DMG: 103.5 MB
Zip: 109.9 MB

I think this is good for now. @Schultzer can you take a 👀 on this and let me know if there's anything else we could rip out of third party dependencies.

2016-10-07 22:39 UTC, danschultzer commented
Removed a lot of unnecessary opencv libraries.

Current file size is 302.6 MB. Breakdown:

- `app.asar`: 49.6 MB
- `thirdparty`: 143.1 MB
  - `thirdparty/dependencies`: 20.7 MB
  - `thirdparty/opencv`: 12 MB
  - `thirdparty/poppler`: 14.8 MB
  - `thirdparty/tesseract`: 95.6 MB
  
DMG: 94.2 MB
Zip: 99.1 MB

2016-10-07 23:07 UTC, danschultzer commented
I've added all eng related `tessdata` files now since we excluded quite a bit by just using `eng.traineddata`. Also made Travis cache much smaller by not caching `tessdata-master`.

2016-10-08 05:00 UTC, danschultzer commented
Removed a lot of unnecessary modules, but this causes issues upstream with `node-opencv`. I'll see if I can make a temporary fix that we can use.

2016-10-09 02:45 UTC, danschultzer commented
Was a lot of work to get [node-opencv](https://github.com/peterbraden/node-opencv) to work with available modules, but it's working now. I'll put up a PR soon to fix it upstream, but for now, we'll just use the branch to build.

2016-10-16 19:06 UTC, danschultzer commented
The last detail in this is `libopenjpeg` and `jasper`. `Poppler` throws this warning when we compile it without `libopenjpeg`:

> Warning: Using libopenjpeg is recommended. The internal JPX decoder is unmaintained.

I'm not sure if we should support JPEG 2000 (`.jp2` and `.jpx`) or not. I would vote for disabling support completely, but we can do a quick test with PDF containing jpeg 2K images to see how it'll work or break.

The support is limited: http://caniuse.com/#feat=jpeg2000

2016-10-16 21:32 UTC, danschultzer commented
Removed `libopenjpeg` completely. Ready for final review, and this can be merged in.

2016-10-17 03:51 UTC, Schultzer requested changes
We should follow #21 with a uniform syntax and use single quotation marks and only use double quotation marks when escaping single quotation in out JS code base.

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +if (process.platform == 'darwin') {
`(process.platform == 'darwin')` this should be `(process.platform === 'darwin')`

2016-10-17 03:51 UTC, Schultzer commented on scripts/build/darwin/opencv.sh
> +    -D BUILD_opencv_highgui=OFF -D BUILD_opencv_flann=OFF -D BUILD_opencv_ml=OFF -D BUILD_opencv_calib3d=OFF -D BUILD_opencv_videoio=OFF -D BUILD_opencv_video=OFF -D BUILD_opencv_videostab=OFF -D BUI
`-DBUILD_opencv_python=OFF`  This should be `-D BUILD_opencv_python=OFF`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    "$PATH",
`"$PATH"` should be `'$PATH'` we should use single quotation marks for strings

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/poppler/bin",
`"/poppler/bin"` should be `'/poppler/bin'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/tesseract/bin"
`"/tesseract/bin"` should be `/tesseract/bin`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    "$DYLD_LIBRARY_PATH",
`"$DYLD_LIBRARY_PATH"` should be `'$DYLD_LIBRARY_PATH'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    "/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/", // Core Graphics package
`"/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/"` should be `'/System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/dependencies/lib",
`"/dependencies/lib"` should be `'/dependencies/lib'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/poppler/lib",
`"/poppler/lib"` should be `'/poppler/lib'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/opencv/lib",
`"/opencv/lib"` should be `'/opencv/lib'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +    thirdpartyPath + "/tesseract/lib"
`"/tesseract/lib"` should be `'/tesseract/lib'`

2016-10-17 03:51 UTC, Schultzer commented on src/utils/thirdparty_env.js
> +  env.TESSDATA_PREFIX = thirdpartyPath + "/tesseract/share/tessdata";
`"/tesseract/share/tessdata"` should be `'/tesseract/share/tessdata'`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +            gutil.log("No build file for", gutil.colors.cyan("'" + platform + "'"));
`gutil.log("No build file for", gutil.colors.cyan("'" + platform + "'"));` should be `gutil.log('No build file for', "'" +  gutil.colors.cyan(platform) + "'");` we don't want the qutation marks to be cyan but white.

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +          gutil.log("Going to build for", gutil.colors.cyan("'" + platform + "'"));
`gutil.log("Going to build for", gutil.colors.cyan("'" + platform + "'"));` should be `gutil.log('Going to build for', "'" +  gutil.colors.cyan(platform) + "'");`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +            "BUILDDIR=" + buildDir,
`"BUILDDIR="` should be `'BUILDDIR='`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +            "THIRDPARTYDIR=" + buildDestDir,
`"THIRDPARTYDIR="` should be `'THIRDPARTYDIR='`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +          ].join(" ");
`join(" ");` should be `join(' ');`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +                  gutil.log("Build succesful");
`gutil.log("Build succesful");` should be `gutil.log('Build succesful');`

2016-10-17 03:51 UTC, Schultzer commented on tasks/build_app.js
> +                  gutil.log("Build failed");
`gutil.log("Build failed");` should be `gutil.log('Build failed');`

2016-10-17 04:13 UTC, Schultzer approved these changes

2016-10-17 04:28 UTC, merged